"""index links by creator

Revision ID: 11fd513276d8
Revises: 2f76d4b1e70d
Create Date: 2026-10-06 07:07:19.554459

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11fd513276d8"
down_revision: str | Sequence[str] | None = "2f76d4b1e70d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_links_created_by"), "links", ["created_by"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_links_created_by"), table_name="links")
    # ### end Alembic commands ###
