"""add links and qr codes

Revision ID: 9ef9a4af9e0f
Revises: 3ddd26533648
Create Date: 2026-10-06 06:23:39.498421

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ef9a4af9e0f"
down_revision: str | Sequence[str] | None = "3ddd26533648"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qr_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qr_codes")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_qr_codes_storage_key")),
    )
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("src", sa.Text(), nullable=False),
        sa.Column("dst", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_to", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["connected_to"],
            ["qr_codes.id"],
            name=op.f("fk_links_connected_to_qr_codes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_links")),
        sa.UniqueConstraint("dst", name=op.f("uq_links_dst")),
    )
    op.create_index(op.f("idx_links_connected_to"), "links", ["connected_to"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_links_connected_to"), table_name="links")
    op.drop_table("links")
    op.drop_table("qr_codes")
    # ### end Alembic commands ###
